Repository dev-jeonggu/2-jeonggu-kim-community-be, pull requests merged in 2024-12, with the labels that each got.

#25 fix : board author display bug
  app/models/boardModel.js
Labels: fix

#26 refactor : image upload methods
  app.js
  app/controllers/boardController.js
  app/controllers/commonController.js
  app/controllers/userController.js
  app/models/boardModel.js
  app/routes/boardRoutes.js
  app/routes/commonRoutes.js
  app/routes/userRoutes.js
  package-lock.json
  package.json
Labels: enhancement, fix

#27 fix: re-add image loading on server
  app/controllers/boardController.js
  app/controllers/userController.js
  app/routes/boardRoutes.js
  app/routes/userRoutes.js
Labels: fix

#31 Add "edited" status detection for posts and comments
  app/models/boardModel.js
  app/models/commentModel.js
Labels: enhancement

#32 Add infinity loading feature
  app/controllers/boardController.js
  app/models/authModel.js
  app/models/boardModel.js
Labels: enhancement

#33 Add image compress
  app/controllers/commonController.js
  package-lock.json
  package.json
Labels: enhancement
